### ISSUE TITLE
No issue, just thanks!

### ISSUE THREAD

**Issue by rogierlommers** [skoef/gop1#1]
Jow man, good to see Dutch Go development! Will use this package to send data to pvoutput.org.
Any tips regarding which cable to use? For example, would [this cable](https://www.bol.com/nl/p/slimme-meter-kabel-p1-usb/9200000111535827/) do this job you think?

**Comment by skoef** [comment]
Thanks Rogier, that's always good to hear! Let me know if the library lacks support for anything and I'll be happy to implement it for you!

I'm using this [cable](https://webshop.cedel.nl/Slimme-meter-kabel-P1-naar-USB), connected to a raspberry pi running microk8s to orchestrate some pods for P1 measurement, influxdb, grafana etc. Works fine!

**Comment by skoef** [comment]
Oh, I just noticed that is the exact same cable you're mentioning!

**Comment by rogierlommers** [comment]
Cool; will order the cable today. Are you also using pvoutput or do you only store the data in your own influxdb instance?

**Comment by skoef** [comment]
I didn't know pvoutput.org before, but now I do I and I like it! I wrote a [little API client](https://github.com/skoef/pvoutput) for it as well!

**Comment by rogierlommers** [comment]
haha, damn! You beat me! (I was planning to do this soon)

**Comment by rogierlommers** [comment]
One last question: do you perhaps also have a way to read values from a SMA inverter? (the sunnyboy 3.6)
Or do you only track / measure energy consumption through P1?

**Comment by skoef** [comment]
I have no experience with that, I only track the P1 data concerning electricity usage/generation
